/*****************************************************************************
  OME-TIFF definitions 
  Copyright (c) 2009, Center for Bio-Image Informatics, UCSB
 
  Author: Dima V. Fedorov <mailto:dima@dimin.net> <http://www.dimin.net/>
    
  History:
    2009-07-09 12:01 - First creation

  Ver : 1
*****************************************************************************/

#ifndef BIM_OMETIFF_FORMAT_H
#define BIM_OMETIFF_FORMAT_H

#include <vector>
#include <string>

#include <xstring.h>
#include <bim_img_format_interface.h>

//----------------------------------------------------------------------------
// OME-TIFF Structure 
//----------------------------------------------------------------------------

namespace bim {

class OMETiffInfo {
public:
    OMETiffInfo(): pages(0), channels(0), bim_order("XYCZT") {}

    uint64 pages;    // the value of consequtive images generated by driver
    int channels;
    uint64 width;
    uint64 height;
    uint64 number_t;
    uint64 number_z;
    xstring bim_order;
    double pixel_resolution[4];

    std::vector<std::string> sample_names;
    std::vector<int> display_lut; // rgb -> chan numbers
};

} // namespace bim

#endif // BIM_OMETIFF_FORMAT_H
