/* jconfigint.h.  Generated by configure.  */
/* libjpeg-turbo build number */
#define BUILD "20150113"

/* How to obtain function inlining. */
#if defined WIN32 || defined WIN64 || defined _WIN32 || defined _WIN64 || defined _MSVC

#ifndef INLINE
#if defined(__GNUC__)
#define INLINE inline __attribute__((always_inline))
#elif defined(_MSC_VER)
#define INLINE __forceinline
#else
#define INLINE
#endif
#endif

#else

#define INLINE inline __attribute__((always_inline))

#endif

/* Define to the full name of this package. */
#define PACKAGE_NAME "libjpeg-turbo"

/* Version number of package */
#define VERSION "1.4.0"
